export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

[[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]] \
  && source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# Exports
export CONFIG="$HOME/.config/"
export PATH=$HOME/.local/bin:$PATH
export PATH=/opt/cuda/include:$PATH
fpath+=( ~/func )
autoload -Uz myfunc
fpath+="$CONFIG/zsh/func"
export SCRIPTS="$HOME/.scripts/"
export PYTHON_ENV="/home/guidiamond/.virtualenv/nvim"
# export ZSH="$HOME/.local/share/zinit/zinit.git"
export EDITOR="nvim"
export UPDATE_ZSH_DAYS=7 # Auto update weekly




# Sources
[ -f "/usr/share/nvm/init-nvm.sh" ] && source /usr/share/nvm/init-nvm.sh
[ -f $CONFIG/zsh/zinit.zsh ] && source $CONFIG/zsh/zinit.zsh
[ -f $CONFIG/fzf/completion.zsh ] && source $CONFIG/fzf/completion.zsh
[ -f $CONFIG/fzf/key-bindings.zsh ] && source $CONFIG/fzf/key-bindings.zsh
[ -f $CONFIG/zsh/fzf-history.zsh ] && source $CONFIG/zsh/fzf-history.zsh
[ -f $CONFIG/zsh/workflow-history.zsh ] && source $CONFIG/zsh/workflow-history.zsh
[ -f $SCRIPTS/alias.sh ] && source $SCRIPTS/alias.sh
[ -f $PYTHON_ENV/bin/activate ] && source $PYTHON_ENV/bin/activate

[ -n "$DISPLAY" ] && xset b off # Turn off beep on typing

# place this after nvm initialization! (source init-nvm)
autoload -U add-zsh-hook

load-nvmrc() {
  local nvmrc_path
  nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version
    nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$(nvm version)" ]; then
      nvm use
    fi
  elif [ -n "$(PWD=$OLDPWD nvm_find_nvmrc)" ] && [ "$(nvm version)" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}

add-zsh-hook chpwd load-nvmrc
load-nvmrc

HISTSIZE=50000
SAVEHIST=$HISTSIZE
HISTFILE=~/.local/share/zsh/history
HIST_STAMPS="dd.mm.yyyy"
CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="true"

# Custom widget to delete a word or a single non-alphanumeric character
backward-kill-alnum-word() {
  # Check if the character to the left of the cursor is a letter or number
  if [[ ${BUFFER[CURSOR]} =~ '[[:alnum:]]' ]]; then
    # If it is, delete backwards until a non-alphanumeric char is found
    while [[ ${BUFFER[CURSOR]} =~ '[[:alnum:]]' && $CURSOR -gt 0 ]]; do
      zle .backward-delete-char
    done
  else
    # Otherwise (if it's a symbol or space), just delete that single character
    zle .backward-delete-char
  fi
}

# Register the function as a Zle (Zsh Line Editor) widget
zle -N backward-kill-alnum-word

# Bind the Alt+Backspace key sequence to your new widget
bindkey '^[^?' backward-kill-alnum-word
## Options section
setopt correct                                                  # Auto correct mistakes
setopt extendedglob                                             # Extended globbing. Allows using regular expressions with *
setopt nocaseglob                                               # Case insensitive globbing
setopt rcexpandparam                                            # Array expension with parameters
setopt nocheckjobs                                              # Don't warn about running processes when exiting
setopt numericglobsort                                          # Sort filenames numerically when it makes sense
setopt nobeep                                                   # No beep
setopt appendhistory                                            # Immediately append history instead of overwriting
setopt histignorealldups                                        # If a new command is a duplicate, remove the older one
setopt autocd                                                   # if only directory path is entered, cd there.
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt extended_history                                         # Save timestamp and duration to history
setopt MENU_COMPLETE
setopt inc_append_history                                       # To save every command before it is executed
setopt share_history                                            # To read the history file everytime history is called upon

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'       # Case insensitive tab completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"         # Colored completion (different colors for dirs/files/etc)
zstyle ':completion:*' rehash true                              # automatically find new executables in path 
zstyle ':completion:*' menu yes select                          # AutoComplete
# Speed up completions
zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

copybuffer () {
  if which clipcopy &>/dev/null; then
    printf "%s" "$BUFFER" | clipcopy
  else
    echo "clipcopy function not found. Please make sure you have Oh My Zsh installed correctly."
  fi
}

zle -N copybuffer
bindkey "^O" copybuffer

function kport() {
  echo "$0"
  #"sudo kill $(lsof -t -i:$0)"
}

# # PyEnv Setup
# eval "$(pyenv init --path)"          # Configure global PATH for pyenv
# eval "$(pyenv init -)"               # Setup pyenv shims and version switching

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"
