[[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]] \
  && source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# Exports
export _JAVA_AWT_WM_NONREPARENTING=1
export CONFIG="$HOME/.config/"
export PATH=/home/damndiamond/.local/bin:$PATH
export SCRIPTS="$HOME/.scripts/"
export PYTHON_ENV="/home/damndiamond/.virtualenv/cloud"
export ZSH="$HOME/.zinit"
export EDITOR="nvim"
export UPDATE_ZSH_DAYS=7 # Auto update weekly

# Sources
[ -f "/usr/share/nvm/init-nvm.sh" ] && source /usr/share/nvm/init-nvm.sh
[ -f $CONFIG/zsh/zinit.zsh ] && source $CONFIG/zsh/zinit.zsh
[ -f $CONFIG/fzf/completion.zsh ] && source $CONFIG/fzf/completion.zsh
[ -f $CONFIG/fzf/key-bindings.zsh ] && source $CONFIG/fzf/key-bindings.zsh
[ -f $SCRIPTS/alias.sh ] && source $SCRIPTS/alias.sh
[ -f $PYTHON_ENV/bin/activate ] && source $PYTHON_ENV/bin/activate

[ -n "$DISPLAY" ] && xset b off # Turn off beep on typing

HISTSIZE=2000
SAVEHIST=$HISTSIZE
HISTFILE=~/.cache/zsh/history
HIST_STAMPS="dd.mm.yyyy"
CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="true"

## Options section
setopt correct                                                  # Auto correct mistakes
setopt extendedglob                                             # Extended globbing. Allows using regular expressions with *
setopt nocaseglob                                               # Case insensitive globbing
setopt rcexpandparam                                            # Array expension with parameters
setopt nocheckjobs                                              # Don't warn about running processes when exiting
setopt numericglobsort                                          # Sort filenames numerically when it makes sense
setopt nobeep                                                   # No beep
setopt appendhistory                                            # Immediately append history instead of overwriting
setopt histignorealldups                                        # If a new command is a duplicate, remove the older one
setopt autocd                                                   # if only directory path is entered, cd there.
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt MENU_COMPLETE
setopt inc_append_history                                       # To save every command before it is executed
setopt share_history                                            # To read the history file everytime history is called upon

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'       # Case insensitive tab completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"         # Colored completion (different colors for dirs/files/etc)
zstyle ':completion:*' rehash true                              # automatically find new executables in path 
zstyle ':completion:*' menu yes select                          # AutoComplete
# Speed up completions
zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

copybuffer () {
  if which clipcopy &>/dev/null; then
    printf "%s" "$BUFFER" | clipcopy
  else
    echo "clipcopy function not found. Please make sure you have Oh My Zsh installed correctly."
  fi
}

zle -N copybuffer
bindkey "^O" copybuffer

function kport() {
  echo "$0"
  #"sudo kill $(lsof -t -i:$0)"
}
