#!/bin/bash

EXTERNAL_REPOS=( ["autonomoAPI"]="src/autonomo" ["loanAPI"]= "src/loan" )

function helpParams() {
  echo "Available Params:"
  echo "-g: get process id on click"
  echo "-k: kill process on click"
}

function validateNoArgs() {
  if [ "$1" == "" ];then
    helpParams;exit 1
  fi
}

#function update() {
  #if []
#}

function main(){
  while getopts ":p" flag; do
    case $flag in
      p) git pull origin master && git subtree pull --prefix src/core backend-core master --squash && ;;
      h) helpParams;exit 1;;
      \?) helpParams;exit 1;;
    esac
  done
}

validateNoArgs $1;main $@
