#!/bin/bash

function helpParams() {
  echo "Available Params:"
  echo "-g: get process id on click"
  echo "-k: kill process on click"
}

function validateNoArgs() {
  if [ "$1" == "" ];then
    helpParams;exit 1
  fi
}

function main(){
  while getopts ":kg" flag; do
    case $flag in
      k) xkill;;
      g) xprop _NET_WM_PID | cut -d' ' -f3;;
      h) helpParams;exit 1;;
      \?) helpParams;exit 1;;
    esac
  done
}

validateNoArgs $1;main $@
