#!/bin/bash

function helpParams() {
  echo "Available Params:"
  echo "-p: update pacman"
  echo "-y: update AUR"
  echo "-a: update pacman and AUR"
  echo "--y: yes option"
}

function validateNoArgs() {
  if [ "$1" == "" ];then
    helpParams;exit 1
  fi
}

function main(){
  while getopts ":pya" flag; do
    case $flag in
      p) sudo pacman -Syu;;
      y) yay -Syu;; 
      a) sudo pacman -Syu && yay -Syu;; 
      h) helpParams;exit 1;;
      \?) helpParams;exit 1;;
    esac
  done
}

validateNoArgs $1;main $@
