#!/bin/bash

function helpParams() {
  echo "Available Params:"
  echo "-u: get users"
  echo "-d: get documentos"
}

function validateNoArgs() {
  if [ "$1" == "" ];then
    helpParams;exit 1
  fi
}

function main(){
  while getopts ":ud" flag; do
    case $flag in
      u) mongoexport -u baduk-admin -p b4zh52HD9TkuczHw --uri "mongodb://ec2-177-71-137-187.sa-east-1.compute.amazonaws.com:27017/baduk" --collection=users --type=json -o users.json;;
      d) mongoexport -u baduk-admin -p b4zh52HD9TkuczHw --uri "mongodb://ec2-177-71-137-187.sa-east-1.compute.amazonaws.com:27017/baduk" --collection=documentos --type=json -o documentos.json;;
      h) helpParams;exit 1;;
      \?) helpParams;exit 1;;
    esac
  done
}

validateNoArgs $1;main $@
