#!/bin/bash

RG=$(curl -s 'https://www.4devs.com.br/ferramentas_online.php' \
  -H 'authority: www.4devs.com.br' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'accept: */*' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36' \
  -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'sec-gpc: 1' \
  -H 'origin: https://www.4devs.com.br' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://www.4devs.com.br/gerador_de_rg' \
  -H 'accept-language: en-US,en;q=0.9' \
  --data-raw 'acao=gerar_rg&pontuacao=N' \
  --compressed)

CNPJ=$(curl -s 'https://www.4devs.com.br/ferramentas_online.php' \
    -H 'authority: www.4devs.com.br' \
    -H 'pragma: no-cache' \
    -H 'cache-control: no-cache' \
    -H 'accept: */*' \
    -H 'x-requested-with: XMLHttpRequest' \
    -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36' \
    -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \
    -H 'sec-gpc: 1' \
    -H 'origin: https://www.4devs.com.br' \
    -H 'sec-fetch-site: same-origin' \
    -H 'sec-fetch-mode: cors' \
    -H 'sec-fetch-dest: empty' \
    -H 'referer: https://www.4devs.com.br/gerador_de_cnpj' \
    -H 'accept-language: en-US,en;q=0.9' \
    --data-raw 'acao=gerar_cnpj&pontuacao=N' \
    --compressed)

CPF=$(curl -s 'https://www.4devs.com.br/ferramentas_online.php' \
  -H 'authority: www.4devs.com.br' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'accept: */*' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36' \
  -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'sec-gpc: 1' \
  -H 'origin: https://www.4devs.com.br' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://www.4devs.com.br/gerador_de_cpf' \
  -H 'accept-language: en-US,en;q=0.9' \
  --data-raw 'acao=gerar_cpf&pontuacao=N&cpf_estado=' \
  --compressed)

echo "CNPJ: ${CNPJ}  "
echo "CPF: ${CPF}  "
echo "RG: ${RG}  "
