#!/bin/bash

# start session
SESSION="baduk-backend-start"
IS_RUNNING=` ! tmux has-session -t ${SESSION} > /dev/null 2>&1 && echo "false"`
baseDIR="$HOME/Documents/work/git/backend"
DIRS=( "userauth" "gateway" "autonomo" "loan" "email" "docs" )
SESSION_SIZE=${#DIRS[@]}
DOCKER_RABBITMQ='rabbitmq'

start_postman() {
  is_postman="pgrep -c electron"
  if [ $is_postman -eq 0]; then
    postman & disown
  fi
}

start_mongo() {
  ! systemctl is-active --quiet mongodb.service && systemctl start mongodb.service && 
    sleep 1
  }

start_rabbitmq() {
  ! systemctl is-active --quiet docker && systemctl start docker && \
    docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
    #(docker start ${DOCKER_RABBITMQ} || docker run -d --hostname my-rabbit --name ${DOCKER_RABBITMQ} rabbitmq:3)
    sleep 1
}


#start_postman
#start_rabbitmq
#start_mongo

if [ "${IS_RUNNING}" == "false" ]; then
  cd $baseDIR
  tmux new-session -d -s $SESSION
  for i in "${!DIRS[@]}"
  do
    idx=$(($i+1))
    tmux new-window -t "$SESSION:$idx" -n ${DIRS[$i]}
    tmux rename-window -t "$SESSION:$idx" ${DIRS[$i]}
    tmux send-keys -t ${DIRS[$i]} "cd ${DIRS[$i]} && clear" C-m
    if [ "${DIRS[$i]}" == "emailAPI" ]; then
      tmux send-keys -t ${DIRS[$i]} "source $HOME/.virtualenv/emailAPI/bin/activate " C-m
      tmux send-keys -t ${DIRS[$i]} "python app.py" C-m
    else
      tmux send-keys -t ${DIRS[$i]} "yarn dev" C-m
    fi
  done
  MONGOIDX=$(($SESSION_SIZE+1))
  tmux new-window -t "$SESSION:$MONGOIDX" -n "MONGO"
  tmux rename-window -t "$SESSION:$MONGOIDX" "MONGO"
  tmux send-keys -t  "MONGO" "mongo" C-m
fi
tmux attach-session -t $SESSION:1
