#!/bin/bash

pic_dir=$HOME/Pictures/qrcodes
mkdir -p "$pic_dir"
clipboard_value=`xclip -o`
qrencode -s 16 -m 2 -o "${pic_dir}/temp_qr.png" "$clipboard_value"
feh --title "qr_generate" --geometry 900x900 --auto-zoom "${pic_dir}/temp_qr.png"
