[module/backlight]
type = internal/xbacklight

; XRandR output to get get values from
; Default: the monitor defined for the running bar
output = eDP-1 HDMI-1

; Create scroll handlers used to set the backlight value
; Default: true
enable-scroll = true


label = %percentage%%
