#!/bin/sh
# Simple script to toggle a node to fullscreen mode in bspwm
FOCUSED_MONITOR=$(bspc query -M -d focused --names)
MAIN_MONITOR="DVI-I-1"
SECONDARY_MONITOR="DVI-D-0"
WORKSPACE_NUMBER=${2}

if [ $FOCUSED_MONITOR == $MAIN_MONITOR ];then
  WORKSPACE_NUMBER=$((WORKSPACE_NUMBER+10))
fi
bspc ${1} \^$WORKSPACE_NUMBER --focus
