font_family      SauceCodePro Nerd Font
# font_family      FiraCode Nerd Font
bold_font        SauceCodePro Nerd Font
italic_font      SauceCodePro Nerd Font
bold_italic_font SauceCodePro Nerd Font


font_size 18.0

background #282c34
foreground #dcdfe4
background_opacity 0.85


map alt+c copy_to_clipboard
map alt+v paste_from_clipboard

map ctrl+equal change_font_size all +2.0
map ctrl+0 change_font_size all 0
map ctrl+minus change_font_size all -2.0

clipboard_control write-clipboard write-primary
