#!/bin/sh
# Simple script to toggle a node to fullscreen mode in bspwm
MONITORS=($(xrandr --listactivemonitors | awk '{print $4}'))
MAIN_MONITOR="${MONITORS[0]}"
OLD_NODE=$(bspc query -N -n focused.local)
bspc node -f ${1}
NEW_NODE=$(bspc query -N -n focused.local)
FOCUSED_MONITOR=$(bspc query -M -d focused --names)
if [ $OLD_NODE == $NEW_NODE ];then
  bspc monitor --focus next

  if [ $FOCUSED_MONITOR == $MAIN_MONITOR ];then
    bspc node -f west
  else
    bspc node -f east
  fi
fi
