#!/bin/sh
# Simple script to toggle a node to fullscreen mode in bspwm
FOCUSED_MONITOR=$(bspc query -M -d focused --names)

MONITORS=($(xrandr --listactivemonitors | awk '{print $4}'))
MAIN_MONITOR="${MONITORS[0]}"

WORKSPACE_NUMBER=${2}

if [ $FOCUSED_MONITOR != $MAIN_MONITOR ];then
  WORKSPACE_NUMBER=$((WORKSPACE_NUMBER+10))
fi
bspc ${1} \^$WORKSPACE_NUMBER --focus
