#!/usr/bin/env bash

# Launch EWW bar on all active monitors
# Usage: ~/.config/eww/launch_bar.sh
# Does NOT touch Polybar or bspwm config.

EWW_DIR="$HOME/.config/eww"
GENERATED="$EWW_DIR/_monitors.yuck"
POSITION_FILE="$EWW_DIR/.bar_position"

# Kill existing eww daemon
eww kill 2>/dev/null
sleep 0.3

# Start playerctld for media player management
pkill -f "playerctld daemon" 2>/dev/null
playerctld daemon &

# ── Read bar position (top or bottom) ────────────────────────────────

position="top"
if [[ -f "$POSITION_FILE" ]]; then
  position=$(cat "$POSITION_FILE")
fi

if [[ "$position" == "bottom" ]]; then
  anchor="bottom center"
  bar_y="0px"
  bar_width="100%"
  stats_anchor="top left"
  stats_y="3px"
else
  anchor="top center"
  bar_y="4px"
  bar_width="96%"
  stats_anchor="bottom left"
  stats_y="3px"
fi

# ── Generate per-monitor config ──────────────────────────────────────
# Each monitor gets its own deflisten + defwindow so workspaces are scoped.

monitors=$(xrandr --listactivemonitors | tail -n +2 | awk '{print $NF}')

: > "$GENERATED"
echo ";; Auto-generated by launch_bar.sh — do not edit" >> "$GENERATED"

for monitor in $monitors; do
  # Sanitize monitor name for use as EWW variable (replace non-alnum with _)
  var="${monitor//[^a-zA-Z0-9]/_}"

  cat >> "$GENERATED" <<EOF

(deflisten workspaces_${var}
  :initial "[]"
  \`~/.config/eww/scripts/workspaces.sh ${monitor}\`)

(deflisten bright_data_${var}
  :initial '{"level":0,"icon":"󰃟","visible":false}'
  \`~/.config/eww/scripts/brightness.sh ${monitor}\`)

(deflisten window_title_${var}
  :initial ""
  \`~/.config/eww/scripts/window_title.sh ${monitor}\`)

(defwindow bar_${var}
           :geometry (geometry :x "0px"
                               :y "${bar_y}"
                               :width "${bar_width}"
                               :height "42px"
                               :anchor "${anchor}")
           :stacking "bottom"
           :windowtype "dock"
           :wm-ignore false
           :exclusive true
  (bar-content :ws-data workspaces_${var} :monitor "${monitor}" :bright-data bright_data_${var} :window-title-data window_title_${var}))

(defwindow stats_${var}
           :geometry (geometry :x "3px"
                               :y "${stats_y}"
                               :width "320px"
                               :height "36px"
                               :anchor "${stats_anchor}")
           :stacking "bottom"
           :windowtype "dock"
           :wm-ignore false
           :exclusive true
  (system-stats-overlay))
EOF
done

# ── Update bspwm padding to match bar position ──────────────────────

# bar=42px + stats=36px + gaps between them and screen edges
if [[ "$position" == "bottom" ]]; then
  bspc config top_padding    44   # stats (top) 36px + 3px offset + margin
  bspc config bottom_padding 52   # bar (bottom) 42px + margin
else
  bspc config top_padding    52   # bar (top) 42px + 4px offset + margin
  bspc config bottom_padding 44   # stats (bottom) 36px + 3px offset + margin
fi

# ── Start daemon and open bars ───────────────────────────────────────

eww daemon --config "$EWW_DIR" &
sleep 0.5

for monitor in $monitors; do
  var="${monitor//[^a-zA-Z0-9]/_}"
  eww open "bar_${var}" \
    --config "$EWW_DIR" \
    --screen "$monitor"
  eww open "stats_${var}" \
    --config "$EWW_DIR" \
    --screen "$monitor"
done

# Start fullscreen watcher (lowers bar when a window goes fullscreen)
pkill -f fullscreen_watcher.sh 2>/dev/null
"$EWW_DIR/scripts/fullscreen_watcher.sh" &

echo "EWW bar launched on all monitors."
