#! /bin/sh 
# Startup #{{{
sxhkd &
setxkbmap -model abnt -layout us -variant intl &&
  xmodmap .Xmodmap &
  nm-applet &
  /home/damndiamond/.config/polybar_ex/launch.sh &
/home/damndiamond/.config/screenlayout/home-monitor.sh &&
  feh --bg-scale --randomize ~/Pictures/Backgrounds &
killall picom && picom --config /home/damndiamond/.config/picom/picom.conf & 
#}}}
# /home/damndiamond/.config/polybar/launch.sh &

# Monitor #{{{
# Monitor principal
bspc monitor DVI-I-1 -d 1 2 3 4 5 6 7 8 9
# Monitor secundario
bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9
#}}}

# Sizing #{{{
bspc config window_gap                    10
bspc config border_width                  3 

bspc config top_padding                   40
bspc config bottom_padding                10
bspc config left_padding                  0
bspc config right_padding                 0
#}}}

# Settings #{{{
bspc config single_monocle                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true

bspc config right_monocle_padding          5
bspc config left_monocle_padding           5
bspc config top_monocle_padding            8
bspc config bottom_monocle_padding         8

# Focus
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config click_to_focus                false

bspc config history_aware_focus           true
bspc config remove_unplugged_monitors     true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4

# Pointer
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#}}}

# Coloring #{{{
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	        "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"
#}}}

# Rules #{{{
#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a /home/damndiamond/.config/polybar_ex/launch.sh)

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#}}}

# vim:foldmethod=marker:foldlevel=0
