#!/bin/bash

# start session
SESSION="baduk-ec2"
IS_RUNNING=` ! tmux has-session -t ${SESSION} > /dev/null 2>&1 && echo "false"`
baseDIR="$HOME/Documents/work/baduk/aws"
PEM_FILE="baduk-ec2.pem";
OS="ubuntu"
DNS_ADMIN="ec2-54-94-118-200.sa-east-1.compute.amazonaws.com"
DNS_MONGO="ec2-177-71-137-187.sa-east-1.compute.amazonaws.com"
DNS="ec2-177-71-145-71.sa-east-1.compute.amazonaws.com"
DNS_BACK="ec2-177-71-233-249.sa-east-1.compute.amazonaws.com"
DNS_BACK_ADMIN="ec2-177-71-174-181.sa-east-1.compute.amazonaws.com"

if [ "${IS_RUNNING}" == "false" ]; then
  cd $baseDIR
  tmux new-session -d -s $SESSION
  tmux new-window -t "1" -n "ec2-admin"
  tmux rename-window -t "1" "ec2-admin"
  tmux send-keys -t "ec2-admin" "ssh -i ${baseDIR}/${PEM_FILE} ${OS}@${DNS_ADMIN}" C-m

  tmux new-window -t "2" -n "ec2-autonomo"
  tmux rename-window -t "2" "ec2-autonomo"
  tmux send-keys -t "ec2-autonomo" "ssh -i ${baseDIR}/${PEM_FILE} ${OS}@${DNS}" C-m

  tmux new-window -t "3" -n "ec2-mongo"
  tmux rename-window -t "3" "ec2-mongo"
  tmux send-keys -t "ec2-mongo" "ssh -i ${baseDIR}/${PEM_FILE} ${OS}@${DNS_MONGO}" C-m

  tmux new-window -t "4" -n "ec2-back"
  tmux rename-window -t "4" "ec2-back"
  tmux send-keys -t "ec2-back" "ssh -i ${baseDIR}/${PEM_FILE} ${OS}@${DNS_BACK}" C-m

  tmux new-window -t "5" -n "ec2-back-admin"
  tmux rename-window -t "5" "ec2-back-admin"
  tmux send-keys -t "ec2-back-admin" "ssh -i ${baseDIR}/${PEM_FILE} ${OS}@${DNS_BACK_ADMIN}" C-m
fi
tmux attach-session -t $SESSION:1
